# Site settings
title: Digital Blog Space
email: "hrsenvar0@gmail.com"
description: "Tech and Travel Photo Journal"
url: "https://hrsenvar.github.io/blog"
#url: ""
baseurl: ""
facebook_username: "hrsenvar"
twitter_username: "hrsenvar"
instagram_username: "hrsenvar"
github_username:  "hrsenvar"
deviantart_username: 
flickr_username: "shaswatgupta"
discus_shortname: "shagup770"
share: true

# Owner/author information
owner:
  name:   Heeraram Senvar
  avatar: heera.jpg
  favicon: favicon.ico
  info: personal website

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : "shagup770"

# Internal nav
nav:
  - GALLERY: "gallery"  
  - JOURNAL: "journal"
  - ABOUT: "about"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
